---
name: Lint
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: poetry setup
        run: |
          pip install poetry
          poetry install
      - name: yamllint
        run: |
          poetry run yamllint .yamllint .github/workflows/
      - name: ruff
        run: |
          poetry run ruff check src tests
          poetry run ruff format --check src tests
